# This is a basic workflow to help you get started with Actions

name: Build Documents

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the main branch
on:
  push:
    branches: [ main, test-* ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    container: ndesign/n-doc:4.5.1
    
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Prepare
    - name: Create gitinfo files for TeX
      run: make hooks && git checkout

    # Runs a single command using the runners shell
    - name: Compile documents
      run: make -j2 delivery

    - name: Archive document snapshots
      run: tar czf MauveCorp_VPN-Client.tar.gz deliverables/*
        
    - name: Upload documents
      uses: actions/upload-artifact@v1
      with:
        name: "CC Documents for MauveCorp VPN Client"
        path: MauveCorp_VPN-Client.tar.gz
    
        
